-- Seed predefined tags for UI type, color, and pattern dimensions
INSERT INTO "tag" ("dimension", "label", "sort_order") VALUES
  ('ui_type', 'Button', 0),
  ('ui_type', 'Card', 1),
  ('ui_type', 'Form', 2),
  ('ui_type', 'Input', 3),
  ('ui_type', 'Modal', 4),
  ('ui_type', 'Navigation', 5),
  ('ui_type', 'Header', 6),
  ('ui_type', 'Hero', 7),
  ('ui_type', 'List', 8),
  ('ui_type', 'Grid', 9),
  ('color', 'Red', 0),
  ('color', 'Orange', 1),
  ('color', 'Yellow', 2),
  ('color', 'Green', 3),
  ('color', 'Blue', 4),
  ('color', 'Purple', 5),
  ('color', 'Pink', 6),
  ('color', 'Neutral', 7),
  ('color', 'Dark', 8),
  ('color', 'Light', 9),
  ('pattern', 'Card layout', 0),
  ('pattern', 'List', 1),
  ('pattern', 'Grid', 2),
  ('pattern', 'Masonry', 3),
  ('pattern', 'Split screen', 4),
  ('pattern', 'Full bleed', 5),
  ('pattern', 'Centered', 6);
