-- Remove pattern tags and replace ui_type with UI Elements from PLANNING docs
DELETE FROM "screenshot_tag" WHERE "tag_id" IN (SELECT "id" FROM "tag" WHERE "dimension" IN ('pattern', 'ui_type'));
DELETE FROM "tag" WHERE "dimension" IN ('pattern', 'ui_type');

-- Insert UI Elements from PLANNING.md (Control, View, Overlay, Imagery)
INSERT INTO "tag" ("dimension", "label", "sort_order") VALUES
  ('ui_type', 'Accordion', 0),
  ('ui_type', 'Button', 1),
  ('ui_type', 'Checkbox', 2),
  ('ui_type', 'Color Picker', 3),
  ('ui_type', 'Date Picker', 4),
  ('ui_type', 'Floating Action Button', 5),
  ('ui_type', 'Radio Button', 6),
  ('ui_type', 'Rating Control', 7),
  ('ui_type', 'Search Bar', 8),
  ('ui_type', 'Segmented Control', 9),
  ('ui_type', 'Slider', 10),
  ('ui_type', 'Stepper', 11),
  ('ui_type', 'Switch', 12),
  ('ui_type', 'Tab', 13),
  ('ui_type', 'Text Field', 14),
  ('ui_type', 'Tile', 15),
  ('ui_type', 'Time Picker', 16),
  ('ui_type', 'Badge', 17),
  ('ui_type', 'Banner', 18),
  ('ui_type', 'Card', 19),
  ('ui_type', 'Carousel', 20),
  ('ui_type', 'Chip', 21),
  ('ui_type', 'Divider', 22),
  ('ui_type', 'Gallery', 23),
  ('ui_type', 'Loading Indicator', 24),
  ('ui_type', 'Map Pin', 25),
  ('ui_type', 'Progress Indicator', 26),
  ('ui_type', 'Side Navigation', 27),
  ('ui_type', 'Skeleton', 28),
  ('ui_type', 'Stacked List', 29),
  ('ui_type', 'Status Dot', 30),
  ('ui_type', 'Tab Bar', 31),
  ('ui_type', 'Table', 32),
  ('ui_type', 'Toolbar', 33),
  ('ui_type', 'Top Navigation Bar', 34),
  ('ui_type', 'Action Sheet', 35),
  ('ui_type', 'Bottom Sheet', 36),
  ('ui_type', 'Coach Marks', 37),
  ('ui_type', 'Dialog', 38),
  ('ui_type', 'Drawer', 39),
  ('ui_type', 'Dropdown Menu', 40),
  ('ui_type', 'Full-Screen Overlay', 41),
  ('ui_type', 'Toast', 42),
  ('ui_type', 'Tooltip', 43),
  ('ui_type', 'Avatar', 44),
  ('ui_type', 'Icon', 45),
  ('ui_type', 'Illustration', 46),
  ('ui_type', 'Logo', 47),
  ('ui_type', 'Photo', 48);
