-- Force new transaction so enum value from 0009 is committed before use
-- (Drizzle runs all migrations in one transaction; PostgreSQL requires enum values to be committed first)
COMMIT;
BEGIN;

-- Seed Screens from PLANNING.md
INSERT INTO "tag" ("dimension", "label", "sort_order") VALUES
  ('screen', 'Audio Player', 0),
  ('screen', 'Audio & Video Recorder', 1),
  ('screen', 'Browser', 2),
  ('screen', 'Calendar', 3),
  ('screen', 'Call', 4),
  ('screen', 'Camera & Scanner', 5),
  ('screen', 'Chat Bot', 6),
  ('screen', 'Date & Time', 7),
  ('screen', 'Dynamic Island', 8),
  ('screen', 'Filters & Stickers', 9),
  ('screen', 'Live Activities', 10),
  ('screen', 'Location & Address', 11),
  ('screen', 'Map', 12),
  ('screen', 'Media Editor', 13),
  ('screen', 'Reminder', 14),
  ('screen', 'Timeline & History', 15),
  ('screen', 'Timer & Clock', 16),
  ('screen', 'Video Player', 17),
  ('screen', 'Widgets', 18),
  ('screen', 'Confetti', 19),
  ('screen', 'Dark Mode', 20),
  ('screen', 'Misc', 21),
  ('screen', 'Article Detail', 22),
  ('screen', 'Augmented Reality', 23),
  ('screen', 'Browse & Discover', 24),
  ('screen', 'Class & Lesson Detail', 25),
  ('screen', 'Emails & Messages', 26),
  ('screen', 'Event Detail', 27),
  ('screen', 'Goal & Task', 28),
  ('screen', 'Home', 29),
  ('screen', 'News Feed', 30),
  ('screen', 'Note Detail', 31),
  ('screen', 'Other Content', 32),
  ('screen', 'Post Detail', 33),
  ('screen', 'Product Detail', 34),
  ('screen', 'Quiz', 35),
  ('screen', 'Recipe Detail', 36),
  ('screen', 'Song & Podcast Detail', 37),
  ('screen', 'Stories', 38),
  ('screen', 'TV Show & Movie Detail', 39),
  ('screen', 'Add & Create', 40),
  ('screen', 'Ban & Block', 41),
  ('screen', 'Cancel', 42),
  ('screen', 'Delete', 43),
  ('screen', 'Draw & Annotate', 44),
  ('screen', 'Edit', 45),
  ('screen', 'Favorite & Pin', 46),
  ('screen', 'Filter & Sort', 47),
  ('screen', 'Flag & Report', 48),
  ('screen', 'Follow & Subscribe', 49),
  ('screen', 'Invite & Refer Friends', 50),
  ('screen', 'Like & Upvote', 51),
  ('screen', 'Move', 52),
  ('screen', 'Other Action', 53),
  ('screen', 'Reorder', 54),
  ('screen', 'Save', 55),
  ('screen', 'Search', 56),
  ('screen', 'Select', 57),
  ('screen', 'Set', 58),
  ('screen', 'Schedule', 59),
  ('screen', 'Share', 60),
  ('screen', 'Transfer & Send Money', 61),
  ('screen', 'Upload & Download', 62),
  ('screen', 'Charts', 63),
  ('screen', 'Dashboard', 64),
  ('screen', 'Progress', 65),
  ('screen', 'Bookmarks & Collections', 66),
  ('screen', 'Downloads & Available Offline', 67),
  ('screen', 'Playlists', 68),
  ('screen', 'Trash & Archive', 69),
  ('screen', 'About', 70),
  ('screen', 'Acknowledgement & Success', 71),
  ('screen', 'Action Option', 72),
  ('screen', 'Confirmation', 73),
  ('screen', 'Empty State', 74),
  ('screen', 'Error', 75),
  ('screen', 'Feature Info', 76),
  ('screen', 'Feedback', 77),
  ('screen', 'Help & Support', 78),
  ('screen', 'Loading', 79),
  ('screen', 'Permission', 80),
  ('screen', 'Privacy Policy', 81),
  ('screen', 'Pull to Refresh', 82),
  ('screen', 'Billing', 83),
  ('screen', 'Cart & Bag', 84),
  ('screen', 'Checkout', 85),
  ('screen', 'Order Confirmation', 86),
  ('screen', 'Order Detail', 87),
  ('screen', 'Order History', 88),
  ('screen', 'Payment Method', 89),
  ('screen', 'Pricing', 90),
  ('screen', 'Promotions & Rewards', 91),
  ('screen', 'Shop & Storefront', 92),
  ('screen', 'Subscription & Paywall', 93),
  ('screen', 'Suggestions & Similar Items', 94),
  ('screen', 'Terms & Conditions', 95),
  ('screen', 'Wallet & Balance', 96),
  ('screen', 'Achievements & Awards', 97),
  ('screen', 'Chat Detail', 98),
  ('screen', 'Comments', 99),
  ('screen', 'Followers & Following', 100),
  ('screen', 'Groups & Community', 101),
  ('screen', 'Invite Teammates', 102),
  ('screen', 'Leaderboard', 103),
  ('screen', 'Notifications', 104),
  ('screen', 'Reviews & Ratings', 105),
  ('screen', 'Social Feed', 106),
  ('screen', 'User / Group Profile', 107),
  ('screen', 'Account Setup', 108),
  ('screen', 'Guided Tour & Tutorial', 109),
  ('screen', 'Splash Screen', 110),
  ('screen', 'Signup', 111),
  ('screen', 'Verification', 112),
  ('screen', 'Welcome & Get Started', 113),
  ('screen', 'Delete & Deactivate Account', 114),
  ('screen', 'Forgot Password', 115),
  ('screen', 'Login', 116),
  ('screen', 'My Account & Profile', 117),
  ('screen', 'Settings & Preferences', 118);
